[tool.poetry]
name = "Schafkopf"
version = "0.1.0"
description = ""
authors = ["ChenStormsout"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
gymnasium = "^0.27.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
